/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.chernikov.Task_2_2_1;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.paint.Color;
import javafx.stage.WindowEvent;
import ru.nsu.fit.chernikov.Task_2_2_1.GameObjects.Direction;
import ru.nsu.fit.chernikov.Task_2_2_1.GameObjects.Level;
import ru.nsu.fit.chernikov.Task_2_2_1.GameObjects.Snake;

public class Game extends Application {
  private static Level level;

  public String getGreeting() {
    return "Hello world.";
  }

  @Override
  public void start(Stage primaryStage) throws Exception {

    FXMLLoader loader = new FXMLLoader(getClass().getResource("/mainScene.fxml"));
    Parent root = loader.load();
    primaryStage.setScene(new Scene(root));
    primaryStage.setResizable(false);
    primaryStage.setTitle("SuperSnake 2000");
    primaryStage
        .getScene()
        .getWindow()
        .addEventFilter(WindowEvent.WINDOW_CLOSE_REQUEST, this::closeWindowEvent);
    primaryStage.show();
  }

  private void closeWindowEvent(WindowEvent event) {
    System.out.println("Have a nice day!");
    System.exit(0);
  }

  Level getLevel() {
    return level;
  }

  public static void main(String[] args) {

    Application.launch();
  }
}
