/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.chernikov.Task_2_2_1;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

/**
 * Application class for running the snake. Relies on static fields so only one entity may be
 * running at a time.
 */
public class Game extends Application {

  private static GameTask gameTask = null;

  @Override
  public void start(Stage primaryStage) throws Exception {
    FXMLLoader loader = new FXMLLoader(getClass().getResource("/mainScene.fxml"));
    Parent root = loader.load();
    primaryStage.setScene(new Scene(root));
    primaryStage.setResizable(false);
    primaryStage.setTitle("SuperSnake 2000");
    primaryStage
        .getScene()
        .getWindow()
        .addEventFilter(WindowEvent.WINDOW_CLOSE_REQUEST, this::closeWindowEvent);
    primaryStage.show();
  }

  /**
   * Set a reference for GameTask object that should be stopped when application is closed.
   *
   * @param gt GameObject to be stopped
   */
  public static void setGameTask(GameTask gt) {
    gameTask = gt;
  }

  private void closeWindowEvent(WindowEvent event) {
    System.out.println("Have a nice day!");
    if (gameTask != null) {
      gameTask.finish();
    }
  }

  public static void main(String[] args) {
    Application.launch();
  }
}
