/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.chernikov;

import org.junit.Test;
import static org.junit.Assert.*;

public class StockTest {
    @Test public void testAppHasAGreeting() {
        Stock classUnderTest = new Stock();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
