/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.chernikov.Task_2_1_1;

import org.junit.Test;
import static org.junit.Assert.*;

public class PizzeriaTest {}
