/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.chernikov;

import java.util.concurrent.Callable;

/**
 * Callable task for determining if an integer is prime. Negative numbers and zero are considered
 * composite.
 */
public class PrimeTask implements Callable<Boolean> {
  private int target;

  /**
   * Create new task with number to determine if is prime.
   *
   * @param number integer to check if prime.
   */
  public PrimeTask(int number) {
    target = number;
  }

  /**
   * Checks if nuber used in constructor is prime.
   *
   * @return true if prime, false if not.
   */
  @Override
  public Boolean call() {
    if (target <= 1) return false;
    for (int i = 2; i * i <= target; i++) {
      if (target % i == 0) {
        return false;
      }
    }
    return true;
  }
}
