/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Task_1_3;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;

public class SubstringSearch {

  /**
   * Search for substring in string. Will return all occurrences.
   *
   * @param string where to look for
   * @param substr what to look for
   * @return ArrayList of all occurrences of substring in string
   */
  public static ArrayList<Integer> search(String string, String substr) {
    int len = string.length();
    ArrayList<Integer> result = new ArrayList<>();
    for (int pos = 0; pos < len; pos++) {
      if (string.substring(pos).startsWith(substr)) {
        result.add(pos);
      }
    }
    return result;
  }

  /**
   * Reads whole file as a String. Warning: String length is int (4 bytes), File length is long (8 bytes).
   *
   * @param fileName path to file
   * @return file content
   * @throws IOException if I/O Exception occurs
   */
  public static String readFileAsString(String fileName) throws IOException {
    return new String(Files.readAllBytes(Paths.get(fileName)));
  }
}
