/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Task_1_3;

import java.io.IOException;
import java.util.ArrayList;
import org.junit.Test;

import static Task_1_3.SubstringSearch.readFileAsString;
import static Task_1_3.SubstringSearch.search;
import static org.junit.Assert.*;

public class SubstringSearchTest {
  private void check(String str, String substr, ArrayList<Integer> positions) {
    int sslen = substr.length();
    for (int pos : positions) {
      assertEquals(substr, str.substring(pos, pos + sslen));
    }
  }

  @Test
  public void testOnFile() {
    String data = null;
    String[] checkList = {"1", "123", "假借字", " ", "\n", "абра", "aaa", "\nqwerty\n", "333"};
    int[] expectedCount = {2, 1, 4, 5, 6, 8, 18, 1, 0};

    try {
      data = readFileAsString("src/test/resources/input.txt");
    } catch (IOException e) {
      System.err.println(e);
      fail();
    }
    for (int i = 0; i < checkList.length; i++) {
      ArrayList<Integer> res = search(data, checkList[i]);
      assertEquals(expectedCount[i], res.size());
      check(data, checkList[i], search(data, checkList[i]));
    }
  }
}
