/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.chernikov.Task_2_2_1;

import org.junit.Test;
import static org.junit.Assert.*;

public class GameTest {
    @Test public void testAppHasAGreeting() {
        Game classUnderTest = new Game();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
