/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.chernikov.Task_1_3;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;

public class SubstringSearch {

  /**
   * Search for substring in a file. Will return ArrayList of all occurrences.
   *
   * @param filename where to look for substring occurrences
   * @param substr what to look for
   * @return ArrayList of all substring occurrences in string
   */
  public static ArrayList<Integer> search(String filename, String substr)
      throws FileNotFoundException {
    int len = substr.length();
    Reader reader = new FileReader(filename);
    ArrayList<Integer> result = new ArrayList<>();
    int substrPos = 0;
    for (substrPos = 0; substrPos < len; substrPos++) {

    }
    return result;
  }
}
